package Entities;

import java.io.File;
import java.io.Serializable;

import Enums.BranchName;
import Enums.Status;
import Enums.UserType;

public class BusinessCustomer implements Serializable {

	/**
	 * @param employerCode
	 * @param employeCompanyName
	 * @param isApproved
	 * @param hRname
	 */
	
	public BusinessCustomer(String employerCode, String employeCompanyName,
					int isApproved, String hRname) {
		super();
		EmployerCode = employerCode;
		EmployeCompanyName = employeCompanyName;
		IsApproved = isApproved;
		HRname = hRname;
	}
	
	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	/**
	 * @return the employerCode
	 */
	public String getEmployerCode() {
		return EmployerCode;
	}
	/**
	 * @return the employeCompanyName
	 */
	public String getEmployeCompanyName() {
		return EmployeCompanyName;
	}
	/**
	 * @return the isApproved
	 */
	public int getIsApproved() {
		return IsApproved;
	}
	/**
	 * @return the hRname
	 */
	public String getHRname() {
		return HRname;
	}
	/**
	 * @param employerCode the employerCode to set
	 */
	public void setEmployerCode(String employerCode) {
		EmployerCode = employerCode;
	}
	/**
	 * @param employeCompanyName the employeCompanyName to set
	 */
	public void setEmployeCompanyName(String employeCompanyName) {
		EmployeCompanyName = employeCompanyName;
	}
	/**
	 * @param isApproved the isApproved to set
	 */
	public void setIsApproved(int isApproved) {
		IsApproved = isApproved;
	}
	/**
	 * @param hRname the hRname to set
	 */
	public void setHRname(String hRname) {
		HRname = hRname;
	}
	/**
	 * Serializable autogenerated serialversion.
	 */
	private static final long serialVersionUID = 9015932894898546590L;
	
	private String EmployerCode;
	private String EmployeCompanyName;
	private int IsApproved;
	private String HRname;

	
	
	
}
