package Entities;

import java.io.File;

import Enums.Branch;
import Enums.Status;
import Enums.UserType;

public class BusinessCustomer extends Customer {

	/**
	 * Serializable autogenerated serialversion.
	 */
	private static final long serialVersionUID = 9015932894898546590L;
	
	private Employer employer;

	public BusinessCustomer(String userName, String password, String firstName, String lastName, String id,
			String email, String phoneNumber, UserType userType, String organization, Branch mainBranch, String role,
			Status status, File avatar, W4CCard w4c, float refundedBalance, Employer employer) {
		super(userName, password, firstName, lastName, id, email, phoneNumber, userType, organization, mainBranch, role,
				status, avatar, w4c, refundedBalance);
		this.employer = employer;
	}

	
	
	
}
