package Entities;

import java.io.File;
import java.io.Serializable;

import Enums.BranchName;
import Enums.Status;
import Enums.UserType;

/**
 * Abstract class to describe a User. Implements Serializable for ocsf.
 * 
 */
public abstract class User implements Serializable {

	/**
	 * Serializable autogenerated serialversion.
	 */
	private static final long serialVersionUID = -8749032741240943517L;

	private String userName;
	private String password;
	private String firstName;
	private String lastName;
	private String id;
	private String email;
	private String phoneNumber;
	private UserType userType;
	private String organization;
	private BranchName mainBranch;
	private String role;
	private int isLoggedIn;
	private Status status;
	private File avatar;
	
	/**
	 * @param userName
	 * @param password
	 * @param firstName
	 * @param lastName
	 * @param id
	 * @param email
	 * @param phoneNumber
	 * @param userType
	 * @param organization
	 * @param mainBranch
	 * @param role
	 * @param status
	 * @param avatar
	 */
	public User(String userName, String password, String firstName, String lastName, String id, String email,
			String phoneNumber, UserType userType, String organization, BranchName mainBranch, String role, Status status,
			File avatar) {
		super();
		this.userName = userName;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.id = id;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.userType = userType;
		this.organization = organization;
		this.mainBranch = mainBranch;
		this.role = role;
		this.status = status;
		this.avatar = avatar;
	}
	

	public void setIsLoggedIn(int isLoggedIn) {
		this.isLoggedIn = isLoggedIn;
	}
	
	public int getIsLoggedIn() {
		return isLoggedIn;
  }
	public User() {
		

	}

	public String getPassword() {
		return password;
	}



	public String getFirstName() {
		return firstName;
	}



	public String getLastName() {
		return lastName;
	}
	
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id=id;
	}


	public String getEmail() {
		return email;
	}



	public String getPhoneNumber() {
		return phoneNumber;
	}



	public UserType getUserType() {
		return userType;
	}



	public String getOrganization() {
		return organization;
	}



	public BranchName getMainBranch() {
		return mainBranch;
	}



	public String getRole() {
		return role;
	}



	public Status getStatus() {
		return status;
	}



	public File getAvatar() {
		return avatar;
	}



	public void setPassword(String password) {
		this.password = password;
	}



	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}



	public void setLastName(String lastName) {
		this.lastName = lastName;
	}



	public void setEmail(String email) {
		this.email = email;
	}



	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}



	public void setUserType(UserType userType) {
		this.userType = userType;
	}



	public void setOrganization(String organization) {
		this.organization = organization;
	}



	public void setMainBranch(BranchName mainBranch) {
		this.mainBranch = mainBranch;
	}



	public void setRole(String role) {
		this.role = role;
	}



	public void setStatus(Status status) {
		this.status = status;
	}



	public void setAvatar(File avatar) {
		this.avatar = avatar;
	}

	public String getUserName() {
		return userName;
	}

	public String toString() {
		return userName;
	}
	
	
}
