package Entities;

import java.io.Serializable;

/**
 * Abstract class to describe a User. Implements Serializable for ocsf.
 * 
 */
public abstract class User implements Serializable {

	/**
	 * Serializable autogenerated serialversion.
	 */
	private static final long serialVersionUID = -8749032741240943517L;

	private String userName;
	private String password;
	private String firstName;
	private String lastName;
	private String id;
	private String email;
	private String phoneNumber;
	private Role role;
	private String organization;
	private Branch mainBranch;

	public User(String userName, String password, String firstName, String lastName, String id, String email,
			String phoneNumber, Role role, String organization, Branch mainBranch) {
		this.userName = userName;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.id = id;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.role = role;
		this.organization = organization;
		this.mainBranch = mainBranch;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getOrganization() {
		return organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public Branch getMainBranch() {
		return mainBranch;
	}

	public void setMainBranch(Branch mainBranch) {
		this.mainBranch = mainBranch;
	}

	public String getUserName() {
		return userName;
	}

	public String toString() {
		return userName;
	}
}
